name: JS SDK for Eoneo V2 CI

on: 
  push:
    branches:
    - uat

jobs:
  build:
    name: release new package and upload to aws s3 bucket - uat environment 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v1
    - name: yarn release
      uses: ./ci-yarn-release
      env:
        DEV_CI_RUNTIME_TOKEN: ${{ secrets.DEV_CI_TOKEN }}
    - name: upload to s3 bucket 
      uses: ./s3-sync-action
      env:
        SOURCE_DIR: '/github/workspace/dist'
        AWS_S3_BUCKET: 'uat.js.eoneopay.com'
        AWS_ACCESS_KEY_ID: ${{ secrets.UAT_AWS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.UAT_AWS_KEY_SECRET }}
        AWS_REGION: ap-southeast-2
        CDN_DISTRIBUTION_ID: E1ARFTGBXVJU1E
